# Generated by Django 3.2.12 on 2022-03-30 10:54

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('full_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='finance.account')),
            ],
            options={
                'ordering': ('full_name',),
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания')),
                ('timepoint', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=30, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Сумма')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Операцию запрещено редактировать')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_operations', to='finance.account', verbose_name='Кредит')),
                ('debet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debet_operations', to='finance.account', verbose_name='Дебет')),
            ],
        ),
        migrations.CreateModel(
            name='IntervalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_day', models.DateField(verbose_name='Первый день периода')),
                ('last_day', models.DateField(verbose_name='Последний день периода')),
                ('operation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='finance.operation', verbose_name='Операция')),
            ],
        ),
    ]
