# Generated by Django 3.2.12 on 2022-03-30 10:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedStatusTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Переходы статусов',
                'verbose_name_plural': 'Переходы статусов',
            },
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
                ('init_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата первого контакта')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('type', models.CharField(choices=[('in', 'Вх.'), ('out', 'Иcх.')], max_length=3, verbose_name='Тип звонка')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='ФИО')),
                ('sex', models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский'), ('couple', 'Семейная пара')], max_length=64, null=True, verbose_name='Пол')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('have_docs', models.BooleanField(default=False, verbose_name='С документами?')),
                ('have_bank_card', models.BooleanField(default=False, verbose_name='Есть банковская карта')),
                ('work_type', models.CharField(blank=True, choices=[('full', 'Постоянная'), ('part', 'Подработка'), ('shift', 'Вахта')], max_length=5, null=True, verbose_name='Тип работы')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Город проживания')),
                ('next_date', models.DateField(blank=True, null=True, verbose_name='Дата следующего контакта')),
                ('comment', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Комментарий')),
                ('last_edited', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время последнего редактирования')),
                ('passport_series', models.CharField(blank=True, max_length=5, null=True, verbose_name='Серия паспорта')),
                ('passport_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='Номер паспорта')),
            ],
            options={
                'verbose_name': 'Соискатель',
                'verbose_name_plural': 'Соискатели',
            },
        ),
        migrations.CreateModel(
            name='ApplicantHistoryHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantHistoryNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Временная метка')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Источник информации',
                'verbose_name_plural': 'Источники информации',
            },
        ),
        migrations.CreateModel(
            name='ApplicantWorkerLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Временная метка')),
                ('comment', models.TextField(verbose_name='Комментарий')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='VacantCustomerLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Доступные объекты',
                'verbose_name_plural': 'Доступные объекты',
            },
        ),
        migrations.CreateModel(
            name='StatusFinal',
            fields=[
                ('status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='final', serialize=False, to='applicants.status', verbose_name='Конечный статус')),
            ],
        ),
        migrations.CreateModel(
            name='StatusInitial',
            fields=[
                ('status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='initial', serialize=False, to='applicants.status', verbose_name='Начальный статус')),
            ],
        ),
        migrations.CreateModel(
            name='StatusOrder',
            fields=[
                ('status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='order', serialize=False, to='applicants.status', verbose_name='Порядок')),
                ('order_int', models.IntegerField(verbose_name='Порядок')),
            ],
        ),
    ]
