# Generated by Django 3.2.12 on 2022-03-30 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('the_redhuman_is', '0001_initial'),
        ('applicants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vacantcustomerlocation',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='the_redhuman_is.customerlocation', verbose_name='Объект'),
        ),
        migrations.AddField(
            model_name='applicantworkerlink',
            name='applicant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_link', to='applicants.applicant', verbose_name='Соискатель'),
        ),
        migrations.AddField(
            model_name='applicantworkerlink',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='applicantworkerlink',
            name='worker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_link', to='the_redhuman_is.worker', verbose_name='Работник'),
        ),
        migrations.AddField(
            model_name='applicanthistorynode',
            name='applicant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='applicants.applicant', verbose_name='Слепок состояния соискателя'),
        ),
        migrations.AddField(
            model_name='applicanthistorynode',
            name='previous',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applicants.applicanthistorynode', verbose_name='Предыдущие состояние'),
        ),
        migrations.AddField(
            model_name='applicanthistoryhead',
            name='applicant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='applicants.applicant', verbose_name='Актуальное состояния соискателя'),
        ),
        migrations.AddField(
            model_name='applicanthistoryhead',
            name='node',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='applicants.applicanthistorynode', verbose_name='Голова списка состояний соискателя'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='citizenship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='the_redhuman_is.country', verbose_name='Гражданство'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='the_redhuman_is.customerlocation', verbose_name='Объект'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='metro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='the_redhuman_is.metro', verbose_name='Метро'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='applicants.applicantsource', verbose_name='Источник'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applicants', to='applicants.status', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='allowedstatustransition',
            name='status_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses_from', to='applicants.status', verbose_name='Из статуса'),
        ),
        migrations.AddField(
            model_name='allowedstatustransition',
            name='status_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses_to', to='applicants.status', verbose_name='В статус'),
        ),
    ]
