# -*- coding: utf-8 -*-

from django.conf.urls import url
from django.urls import path

from the_redhuman_is.views import (
    gt_customer_account,
    gt_customer_account_v2,
)

urlpatterns = [
    # autocomplete
    url(
        r'^request_autocomplete/$',
        gt_customer_account.DeliveryRequestAutocomplete.as_view(),
        name='gt_customer_request_autocomplete'
    ),
    url(
        r'^item_autocomplete/$',
        gt_customer_account.DeliveryItemAutocomplete.as_view(),
        name='gt_customer_item_autocomplete'
    ),
    url(
        r'^location_autocomplete/$',
        gt_customer_account.LocationAutocomplete.as_view(),
        name='gt_customer_location_autocomplete'
    ),

    url(
        r'^signup$',
        gt_customer_account.signup,
        name='gt_customer_signup'
    ),
    url(
        r'^signup/$',
        gt_customer_account.signup,
        name='gt_customer_signup_v1'
    ),
    url(
        r'^finish_registration$',
        gt_customer_account.finish_registration,
        name='gt_customer_finish_registration'
    ),
    url(
        r'^finish_registration/$',
        gt_customer_account.finish_registration,
        name='gt_customer_finish_registration_v1'
    ),
    url(
        r'^obtain_token$',
        gt_customer_account.obtain_token,
        name='gt_customer_obtain_token'
    ),
    url(
        r'^obtain_token/$',
        gt_customer_account.obtain_token,
        name='gt_customer_obtain_token_v1'
    ),
    url(
        r'^reset_password$',
        gt_customer_account.reset_password,
        name='gt_customer_reset_password'
    ),
    url(
        r'^reset_password/$',
        gt_customer_account.reset_password,
        name='gt_customer_reset_password_v1'
    ),
    url(
        r'^update_password$',
        gt_customer_account.update_password,
        name='gt_customer_update_password'
    ),
    url(
        r'^update_password/$',
        gt_customer_account.update_password,
        name='gt_customer_update_password_v1'
    ),
    url(
        r'^account_info/$',
        gt_customer_account.account_info,
        name='gt_customer_account_info'
    ),

    url(
        r'^update_legal_entity_info$',
        gt_customer_account.update_legal_entity_info,
        name='gt_customer_update_legal_entity_info'
    ),
    url(
        r'^update_legal_entity_info/$',
        gt_customer_account.update_legal_entity_info,
        name='gt_customer_update_legal_entity_info_v1'
    ),
    url(
        r'^legal_entity_info/$',
        gt_customer_account.legal_entity_info,
        name='gt_customer_legal_entity_info'
    ),

    url(
        r'^add_contact_person$',
        gt_customer_account.add_contact_person,
        name='gt_customer_add_contact_person'
    ),
    url(
        r'^add_contact_person/$',
        gt_customer_account.add_contact_person,
        name='gt_customer_add_contact_person_v1'
    ),
    url(
        r'^update_contact_person$',
        gt_customer_account.update_contact_person,
        name='gt_customer_update_contact_person'
    ),
    url(
        r'^update_contact_person/$',
        gt_customer_account.update_contact_person,
        name='gt_customer_update_contact_person_v1'
    ),
    url(
        r'^contact_persons/$',
        gt_customer_account.contact_persons,
        name='gt_customer_contact_persons'
    ),
    url(
        r'^get_contract/$',
        gt_customer_account.get_contract,
        name='gt_customer_get_contract'
    ),
    url(
        r'^upload_contract_scans$',
        gt_customer_account.upload_contract_scans,
        name='gt_customer_upload_contract_scans'
    ),
    url(
        r'^upload_contract_scans/$',
        gt_customer_account.upload_contract_scans,
        name='gt_customer_upload_contract_scans_v1'
    ),

    url(
        r'^report_scan/$',
        gt_customer_account.report_scan,
        name='gt_customer_report_scan'
    ),
    url(
        r'^reports/$',
        gt_customer_account.reports,
        name='gt_customer_reports'
    ),
    url(
        r'^confirm_report$',
        gt_customer_account.confirm_report,
        name='gt_customer_confirm_report'
    ),
    url(
        r'^confirm_report/$',
        gt_customer_account.confirm_report,
        name='gt_customer_confirm_report_v1'
    ),

    url(
        r'^imports/$',
        gt_customer_account.imports,
        name='gt_customer_imports'
    ),
    url(
        r'^requests_file/$',
        gt_customer_account.requests_file,
        name='gt_customer_requests_file'
    ),
    url(
        r'^invoice/$',
        gt_customer_account.invoice,
        name='gt_customer_invoice'
    ),
    url(
        r'^invoices/$',
        gt_customer_account.invoices,
        name='gt_customer_invoices'
    ),
    url(
        r'^create_invoice$',
        gt_customer_account.create_invoice,
        name='gt_customer_create_invoice'
    ),
    url(
        r'^create_invoice/$',
        gt_customer_account.create_invoice,
        name='gt_customer_create_invoice_v1'
    ),
    path(
        'daily_reconciliation_confirm/',
        gt_customer_account.daily_reconciliation_confirm,
        name='gt_customer_daily_reconciliation_confirm'
    ),
    path(
        'daily_reconciliation_details/',
        gt_customer_account.daily_reconciliation_details,
        name='gt_customer_daily_reconciliation_detail'
    ),

    path(
        'v2/delivery/request/',
        gt_customer_account_v2.list_requests,
        name='gt_customer_delivery_request'
    ),
    path(
        'v2/delivery/request/detail/',
        gt_customer_account_v2.request_detail,
        name='gt_customer_delivery_request_detail'
    ),
    path(
        'v2/delivery/request/create/',
        gt_customer_account_v2.create_request,
        name='gt_customer_delivery_create_request'
    ),
    path(
        'v2/delivery/request/import/',
        gt_customer_account_v2.import_requests,
        name='gt_customer_delivery_import_requests'
    ),
    path(
        'v2/delivery/request/update/',
        gt_customer_account_v2.update_request,
        name='gt_customer_delivery_update_request'
    ),
    path(
        'v2/delivery/request/item/create/',
        gt_customer_account_v2.create_delivery_item,
        name='gt_customer_delivery_create_item'
    ),
    path(
        'v2/delivery/request/item/update/',
        gt_customer_account_v2.update_item,
        name='gt_customer_delivery_update_item'
    ),
    path(
        'v2/reports/details/',
        gt_customer_account_v2.report_details,
        name='gt_customer_report_details',
    ),
    path(
        'v2/request_photo/',
        gt_customer_account_v2.request_photo,
        name='gt_customer_request_photo'
    ),

    # new api - requests on map

    path(
        'v2/delivery/map/request/',
        gt_customer_account_v2.requests_on_map,
        name='gt_customer_delivery_requests_on_map'
    ),
    path(
        'v2/delivery/map/autocomplete/request/',
        gt_customer_account_v2.MapRequestAutocomplete.as_view(),
        name='gt_customer_delivery_map_request_autocomplete'
    ),
]
