# Generated by Django 3.2.12 on 2022-03-30 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Import',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('file_content', models.TextField()),
                ('file_name', models.CharField(max_length=255)),
                ('comment', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='ImportedNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('hd', 'Header'), ('ai', 'AccountInfo'), ('dt', 'Document')], max_length=2)),
                ('key', models.CharField(max_length=256, null=True, unique=True)),
                ('position_in_file', models.SmallIntegerField()),
                ('items', models.TextField()),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.operation')),
                ('theimport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='import1c.import')),
            ],
        ),
        migrations.CreateModel(
            name='AccountMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_account', models.CharField(max_length=20)),
                ('tax_code', models.CharField(max_length=15)),
                ('budget_code', models.CharField(blank=True, max_length=20, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.account')),
            ],
        ),
    ]
