# Generated by Django 3.2.12 on 2022-03-30 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='id пользователя в телеграме')),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон')),
                ('date', models.DateTimeField(auto_now=True)),
                ('bot', models.CharField(choices=[('office', 'Офисный'), ('alerts', 'Разработческий')], max_length=20, verbose_name='Бот')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'telegram_bot_user',
            },
        ),
        migrations.AddConstraint(
            model_name='telegramuser',
            constraint=models.UniqueConstraint(fields=('user', 'bot'), name='unique_user_bot'),
        ),
    ]
