from django.urls import path

from the_redhuman_is.views.backoffice_app.delivery import (
    autocomplete,
    import_history,
    main_workplace,
    reconciliations,
    reports,
    request_count,
    requests_on_map,
)
from the_redhuman_is.views.backoffice_app import workers

urlpatterns = [
    # common autocomplete
    path(
        'worker_autocomplete/',
        autocomplete.DeliveryWorkerAutocomplete.as_view(),
        name='backoffice_delivery_worker_autocomplete'
    ),
    path(
        'customer_autocomplete/',
        autocomplete.DeliveryCustomerAutocomplete.as_view(),
        name='backoffice_delivery_customer_autocomplete'
    ),
    path(
        'operator_autocomplete/',
        autocomplete.OperatorAutocomplete.as_view(),
        name='backoffice_delivery_operator_autocomplete'
    ),
    path(
        'route_autocomplete/',
        autocomplete.DeliveryRequestAutocomplete.as_view(),
        name='backoffice_delivery_route_autocomplete'
    ),
    path(
        'location_autocomplete/',
        autocomplete.LocationAutocomplete.as_view(),
        name='backoffice_delivery_location_autocomplete'
    ),
    path(
        'service_autocomplete/',
        autocomplete.ServiceAutocomplete.as_view(),
        name='backoffice_delivery_service_autocomplete'
    ),
    path(
        'item_autocomplete/',
        autocomplete.DeliveryItemAutocomplete.as_view(),
        name='backoffice_delivery_item_autocomplete'
    ),
    path(
        'zone_autocomplete/',
        autocomplete.DeliveryZoneAutocomplete.as_view(),
        name='backoffice_delivery_zone_autocomplete'
    ),

    # import history
    path(
        'import_history/',
        import_history.import_history,
        name='backoffice_delivery_import_history'
    ),

    # request count
    path(
        'request_count/',
        request_count.request_count,
        name='backoffice_delivery_request_count'
    ),

    # operators page
    path(
        'call_to_driver/',
        main_workplace.call_to_driver,
        name='backoffice_delivery_call_to_driver'
    ),
    path(
        'calls_report/',
        main_workplace.calls_report,
        name='backoffice_delivery_calls_report'
    ),
    path(
        'ban_worker/',
        main_workplace.ban_worker, # Todo: move to workers
        name='backoffice_delivery_ban_worker'
    ),
    path(
        'unban_worker/',
        main_workplace.unban_worker, # Todo: move to workers
        name='backoffice_delivery_unban_worker'
    ),
    path(
        'set_worker_zone/<int:pk>/',
        main_workplace.set_worker_zone, # Todo: move to workers
        name='backoffice_delivery_set_worker_zone'
    ),

    # reconciliations
    path(
        'reconciliations/calendar/',
        reconciliations.calendar,
        name='backoffice_reconciliations_calendar'
    ),
    path(
        'reconciliations/<int:pk>/',
        reconciliations.detail,
        name='backoffice_reconciliations_detail'
    ),
    path(
        'reconciliations/<int:pk>/confirm/',
        reconciliations.confirm_unconfirm,
        name='backoffice_reconciliations_confirm_unconfirm'
    ),
    path(
        'reconciliations/<int:pk>/email/',
        reconciliations.send_notification_email,
        name='backoffice_reconciliations_send_email'
    ),

    # reports
    path(
        'reports/distribution_by_distance/',
        reports.distribution_by_distance,
        name='backoffice_distribution_by_distance_report'
    ),

    # workers
    path(
        'workers/',
        workers.worker_list,
        name='backoffice_worker_list'
    ),
    path(
        'workers/<int:pk>/',
        workers.worker_detail,
        name='backoffice_worker_detail'
    ),
    path(
        'workers/<int:pk>/tag/set/',
        workers.set_tag,
        name='backoffice_worker_set_tag'
    ),
    path(
        'workers/<int:pk>/comments/add/',
        workers.add_comment,
        name='backoffice_worker_add_comment'
    ),
    path(
        'workers/rating/update/',
        workers.update_worker_rating,
        name='backoffice_worker_update_rating',
    ),
    path(
        'workers/update_online_status/',
        workers.update_online_status,
        name='backoffice_worker_update_online_status',
    ),
    path(
        'workers/set_planned_contact_day/',
        workers.set_planned_contact_day,
        name='backoffice_worker_set_planned_contact_day'
    ),
    path(
        'workers/call/',
        main_workplace.call_to_worker,
        name='backoffice_delivery_call_to_worker'
    ),
    path(
        'workers/bind_to_talk_bank/',
        workers.bind_to_talk_bank,
        name='backoffice_worker_bind_to_talk_bank'
    ),

    # new api - requests
    path(
        'request/',
        main_workplace.list_requests,
        name='backoffice_delivery_request_list'
    ),
    path(
        'request/detail/',
        main_workplace.request_detail,
        name='backoffice_delivery_request_detail'
    ),
    path(
        'request/create/',
        main_workplace.create_request,
        name='backoffice_delivery_create_request'
    ),
    path(
        'request/import/',
        main_workplace.import_requests,
        name='backoffice_delivery_import_requests'
    ),
    path(
        'request/update/',
        main_workplace.update_request,
        name='backoffice_delivery_update_request'
    ),
    path(
        'request/worker/add/',
        main_workplace.add_request_worker,
        name='backoffice_delivery_add_request_worker'
    ),
    path(
        'request/worker/confirm/',
        main_workplace.confirm_request_worker,
        name='backoffice_delivery_confirm_request_worker'
    ),
    path(
        'request/worker/remove/',
        main_workplace.remove_request_worker,
        name='backoffice_delivery_remove_request_worker'
    ),
    path(
        'request/item/create/',
        main_workplace.create_delivery_item,
        name='backoffice_delivery_create_item'
    ),
    path(
        'request/item/update/',
        main_workplace.update_item,
        name='backoffice_delivery_update_item'
    ),
    path(
        'request/item/move/',
        main_workplace.move_delivery_item,
        name='backoffice_delivery_move_item'
    ),
    path(
        'request/item/worker/add/',
        main_workplace.add_item_workers,
        name='backoffice_delivery_add_item_workers'
    ),
    path(
        'request/item/worker/remove/',
        main_workplace.remove_item_worker,
        name='backoffice_delivery_remove_item_worker'
    ),
    path(
        'request/item/worker/delete/',
        main_workplace.delete_item_worker,
        name='backoffice_delivery_delete_item_worker'
    ),
    path(
        'request/item/worker/start/',
        main_workplace.item_worker_start,
        name='backoffice_delivery_item_worker_start'
    ),
    path(
        'request/item/worker/start/photo/reject/',
        main_workplace.item_worker_start_reject_photo,
        name='backoffice_delivery_item_worker_start_photo_reject'
    ),
    path(
        'request/item/worker/start/photo/confirm/',
        main_workplace.item_worker_start_confirm_photo,
        name='backoffice_delivery_item_worker_start_photo_confirm'
    ),
    path(
        'request/item/worker/start/unconfirm/',
        main_workplace.item_worker_start_unconfirm,
        name='backoffice_delivery_item_worker_start_unconfirm'
    ),
    path(
        'request/item/worker/start/confirm/',
        main_workplace.item_worker_start_confirm,
        name='backoffice_delivery_item_worker_start_confirm'
    ),
    path(
        'request/item/worker/start/discrepancy/',
        main_workplace.resolve_discrepancy,
        name='backoffice_delivery_item_worker_start_resolve_discrepancy'
    ),
    path(
        'request/item/worker/finish/',
        main_workplace.item_worker_finish,
        name='backoffice_delivery_item_worker_finish'
    ),
    path(
        'request/item/worker/finish/photo/reject/',
        main_workplace.item_worker_finish_reject_photo,
        name='backoffice_delivery_item_worker_finish_photo_reject'
    ),
    path(
        'request/item/worker/finish/photo/confirm/',
        main_workplace.item_worker_finish_confirm_photo,
        name='backoffice_delivery_item_worker_finish_photo_confirm'
    ),
    path(
        'request/item/worker/finish/unconfirm/',
        main_workplace.item_worker_finish_unconfirm,
        name='backoffice_delivery_item_worker_finish_reject'
    ),
    path(
        'request/item/worker/finish/confirm/',
        main_workplace.item_worker_finish_confirm,
        name='backoffice_delivery_item_worker_finish_confirm'
    ),
    path(
        'request/worker/hours/',
        main_workplace.set_worker_hours,
        name='backoffice_delivery_item_worker_set_hours'
    ),
    path(
        'photos/',  # Todo: needs a better url
        main_workplace.photos_list,
        name='backoffice_photos_dashboard'
    ),
    path(
        'photos/detail/',  # Todo: needs a better url
        main_workplace.photos_detail,
        name='backoffice_photos_dashboard_detail'
    ),
    path(
        'request/photos/',
        main_workplace.extra_photos,
        name='backoffice_delivery_request_extra_photos'
    ),
    path(
        'request/photos/add/',
        main_workplace.add_extra_photos,
        name='backoffice_delivery_request_add_extra_photos'
    ),

    # new api - requests on map
    path(
        'map/request/',
        requests_on_map.requests_on_map,
        name='backoffice_delivery_requests_on_map'
    ),
    path(
        'map/autocomplete/request/',
        requests_on_map.MapRequestAutocomplete.as_view(),
        name='backoffice_delivery_map_request_autocomplete'
    ),
    path(
        'map/autocomplete/worker/',
        requests_on_map.MapWorkerAutocomplete.as_view(),
        name='backoffice_delivery_map_worker_autocomplete'
    ),
    path(
        'worker_map_data/',
        requests_on_map.worker_map_data,
        name='backoffice_delivery_worker_map_data'
    ),

    # new api - reports
    path(
        'v2/reports/day/',
        reports.day_report,
        name='backoffice_delivery_day_report',
    ),
    path(
        'v2/reports/interval/',
        reports.interval_report,
        name='backoffice_delivery_interval_report',
    ),
    path(
        'reports/suspicious_turnouts/',
        reports.suspicious_turnouts_report,
        name='backoffice_delivery_suspicious_turnouts_report',
    ),
]
