# Generated by Django 2.2.26 on 2022-03-15 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_redhuman_is', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryitem',
            name='confirmed_timepoint',
            field=models.TimeField(blank=True, null=True, verbose_name='Согласованное время подачи'),
        ),
    ]
