# Generated by Django 2.2.26 on 2022-03-15 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_redhuman_is', '0003_item_timepoint_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryrequest',
            name='confirmed_timepoint',
        ),
    ]
