# Generated by Django 3.2.12 on 2022-04-21 12:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('the_redhuman_is', '0004_remove_deliveryrequest_confirmed_timepoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalkBankClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.TextField(verbose_name='ID клиента')),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='the_redhuman_is.worker', verbose_name='Работник')),
            ],
        ),
        migrations.CreateModel(
            name='TalkBankBindStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время получения')),
                ('is_bound', models.BooleanField(verbose_name='Самозанятый привязан к ТокБанку')),
                ('operation_result', models.TextField(verbose_name='Код результата операции привязки')),
                ('operation_result_description', models.TextField(verbose_name='Расшифровка результата операции привязки')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='the_redhuman_is.worker', verbose_name='Работник')),
            ],
        ),
        migrations.CreateModel(
            name='PaysheetTalkBankPaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('payment_in_progress', 'В процессе оплаты'), ('payment_complete', 'Успешно завершена'), ('payment_error', 'Ошибка')], default='payment_in_progress', max_length=200, verbose_name='Статус')),
                ('paysheet', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='the_redhuman_is.paysheet_v2', verbose_name='Ведомость')),
            ],
        ),
        migrations.CreateModel(
            name='PaysheetEntryTalkBankPaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(verbose_name='Результат операции выплаты')),
                ('description', models.TextField(verbose_name='Описание результата операции выплаты')),
                ('service_description', models.TextField(blank=True, null=True, verbose_name='Описание услуги')),
                ('paysheet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='the_redhuman_is.paysheet_v2', verbose_name='Ведомость')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='the_redhuman_is.worker', verbose_name='Работник')),
            ],
        ),
        migrations.CreateModel(
            name='PaysheetEntryTalkBankPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_number', models.TextField(verbose_name='ИНН')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Фактическая сумма')),
                ('bank_account', models.TextField(verbose_name='Счет')),
                ('bank_name', models.TextField(verbose_name='Банк')),
                ('bank_identification_code', models.TextField(verbose_name='Бик')),
                ('completed', models.BooleanField(verbose_name='Завершена')),
                ('status', models.TextField(verbose_name='Статус')),
                ('order_slug', models.TextField(verbose_name='ID операции')),
                ('talk_bank_commission', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, verbose_name='Комиссия ТокБанка')),
                ('beneficiary_partner_commission', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, verbose_name='Комиссия партнеров')),
                ('paysheet_entry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='the_redhuman_is.paysheet_v2entry', verbose_name='Запись в ведомости')),
            ],
        ),
    ]
