# Generated by Django 3.2.12 on 2022-08-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_redhuman_is', '0006_workerpoll'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileAppPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Имя партнера')),
                ('api_entry', models.TextField(verbose_name='Корень API для мобильного приложения')),
            ],
        ),
    ]
