# Generated by Django 3.2.12 on 2023-01-05 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('the_redhuman_is', '0007_mobileapppartner'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaysheetEntryTalkBankIncomeRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания')),
                ('income_registration_request', models.TextField(verbose_name='Id запроса')),
                ('date', models.DateField(verbose_name='Дата чека')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Фактическая сумма')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('paysheet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='the_redhuman_is.paysheet_v2', verbose_name='Ведомость')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='the_redhuman_is.worker', verbose_name='Работник')),
            ],
        ),
    ]
