# Generated by Django 3.2.12 on 2023-01-13 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('the_redhuman_is', '0009_talkbankwebhookrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='paysheettalkbankpaymentstatus',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='auth.user', verbose_name='Автор'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paysheettalkbankpaymentstatus',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания'),
        ),
    ]
