# Generated by Django 3.2.12 on 2022-03-30 10:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LastUiscomCallsImportTimepoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timepoint', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время последней выгрузки')),
            ],
        ),
    ]
